### PR TITLE
Adding the backup for part2 

### PR DESCRIPTION
**Pull request by edyoshikun**
This PR adds the backup for part2 at the bottom of part 1. We added the following:

- Learned feature visualization by mapping first 3 principal components to a colormap (i.e magenta, green, blue)
- Exploring the range of validity of the model by adding scaling and gaussian blur. 
-

### CODE REVIEW

**Comment by ziw-liu** [comment]
@edyoshikun can you run black formatting, sort and remove unused import?

**Comment by mattersoflight** [comment]
The introduction should be more intuitive to explain "why" one would want to use virtual staining and how cool this exercise is!

I am not committing my changes, because I haven't setup the environment with `pre-commit`.

Noting my suggestions here for `solution.py`:

Update to overview:
```
# ## Overview

# In this exercise, we will _virtually stain_ the nuclei and plasma membrane from the quantitative phase image (QPI), i.e., translate QPI images into fluoresence images of nuclei and plasma membranes.
# QPI encodes multiple cellular structures and virtual staining decomposes these structures. After the model is trained, one only needs to acquire label-free QPI data.
# This strategy solves the problem as "multi-spectral imaging", but is more compatible with live cell imaging and high-throughput screening.
# Virtual staining is often a step towards multiple downstream analyses: segmentation, tracking, and cell state phenotyping.
# In this exercise, you will train a model to predict the fluorescence images of nuclei and plasma membranes from QPI images, make it robust to variations in imaging conditions using data augmentions, segment the cells, use regression and segmentation metrics to evalute the models, visualize the image transform learned by the model, and understand the failure modes of the trained model.
# [![HEK293T](https://raw.githubusercontent.com/mehta-lab/VisCy/main/docs/figures/svideo_1.png)](https://github.com/mehta-lab/VisCy/assets/67518483/d53a81eb-eb37-44f3-b522-8bd7bddc7755)
# (Click on image to play video)
```

**Comment by adjavon** [comment]
A couple things as I try to run this: 
- The data has moved to `/mnt/efs/dlmbl/share/` but see caveat below
- We can't use `~/data/` as a location for results, can we change`training_top_dir` so that it saves within the same directory as the exercise is (e.g. under `Path(os.getcwd()) / output`)
-  In`log_batch_jupyter`
    - `n_channels` never defined
    - Then when I try to plot the images they show up as empty (black)

**Comment by ziw-liu** [comment]
@edyoshikun The training dataset is set up to use mean/std normalization for both phase and fluorescence (not using median/iqr for fluorescence). Not sure if this is related to the slow convergence.

**Pull request merged**
